### ISSUE TITLE
Abschnitt "SimpleClient anpassen" aktualisieren

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha-enduser-docs#14]
Ich denke der ist noch aus der Zeit, wo wir eine LogicFactory hatten. Jedenfalls steht da noch was von RandomLogic, das heisst jetzt einfach Logic.

**Comment by Xerus2000** [comment]
Ich würde eher SimpleLogic vorschlagen, analog zu SimpleClient. "Logic" klingt für mich nach einer Abstraktion oder generellen Logik.

**Comment by SKoschnicke** [comment]
Das ist insofern die "generelle" Logik als dass es meistens so laufen wird, dass die Schueler die Klasse nehmen und direkt veraendern. Dann ist es nicht so passend, sie "SimpleLogic" zu nennen, oder?

**Comment by Xerus2000** [comment]
Ok. Ich habe sie immer separat aufgehoben als Absicherung bei der Fehlersuche ^^

**Comment by Xerus2000** [comment]
Bitte mit mehr details wieder öffnen wenn dieses Issue noch relevant ist.
