### ISSUE TITLE
XML Doku Piranhas

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha-enduser-docs#16]
Vermutlich kann man viel aus dem letzten Jahr kopieren und anpassen.

**Comment by SKoschnicke** [comment]
@soerendomroes koenntest du das uebernehmen?

**Comment by SKoschnicke** [comment]
Wie siehts hiermit aus?

**Comment by soerendomroes** [comment]
Ich gehe das am Samstag an

**Comment by Xerus2000** [comment]
Bitte beim schließen immer den "Fixes" Syntax im commit body verwenden oder zumindest beim schließen des Issues "Fixed by ..." kommentieren. Also in diesem Fall fixed by c22deb34a2e3453798636833f2f910aa874fcdba wenn ich das richtig sehe.
