### ISSUE TITLE
Java Code Styleguide

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha-enduser-docs#2]
Die original Java Code Style Conventions werden nicht mehr gepflegt und sind nicht mehr unter der URL verfuegbar, wie sie in dieser Anleitung angegeben ist (unter "[Der saubere Programmierstil](https://cau-kiel-tech-inf.github.io/socha-enduser-docs/#_der_saubere_programmierstil)"). Wir sollten besser auf den Google Java Styleguide verweisen:

https://google.github.io/styleguide/javaguide.html

Und die Zusammenfassung in dem Kapitel entsprechend anpassen.

**Comment by Xerus2000** [comment]
Bitte wieder öffnen wenn dieses Issue noch relevant ist.
