### ISSUE TITLE
Regelklarstellung: Gegnerische Fische

### ISSUE THREAD

**Issue by mathiasbockwoldt** [CAU-Kiel-Tech-Inf/socha-enduser-docs#20]
Die Anleitung `/spiele/piranhas/spielregeln/regeln.adoc` sagt:

> Beim Zug darf man Felder mit eigenen Fischen sowie Kraken überspringen, nicht aber Felder mit gegnerischen Fischen.

Heißt das, dass der eigene Fisch bei dem gegnerischen Fisch stoppt (also wenn der Fisch eigentlich 4 Felder schwimmen müsste, nach 2 Feldern aber ein Gegner steht, der eigene Fisch nur 2 Felder schwimmt und den Gegner frisst), oder ist das dann ein ungütliger Zug?

**Comment by soerendomroes** [comment]
Das heißt das der Zug ungültig ist.

**Comment by mathiasbockwoldt** [comment]
Danke für die schnelle Antwort!
