### ISSUE TITLE
Beschreibung zum Erstellen eines Spiels mit Ruby Client

### ISSUE THREAD

**Issue by SKoschnicke** [CAU-Kiel-Tech-Inf/socha-enduser-docs#8]
In der Doku steht (nach commit [41d526846](https://github.com/CAU-Kiel-Tech-Inf/socha-enduser-docs/commit/41d5268461dc064882ac544626bdd9b2e05dd931)):

> direkt aufrufen (kein Java Client): Bei Spielertyp ‚Computerspieler’ kann man durch aktivieren dieser Option erreichen, dass das ausgewählte Programm nicht wie ein Java Client gestartet wird (es ist also keine Jar-Datei). Wenn die Option activity ist, wird das ausgewählte Programm direkt aufgerufen. Die Daten zum Server und die Reservierungs-Nummer für das Spiel werden aber in jedem Fall als Parameter übergeben. Soll zum Beispiel der ruby simple-client gestartet werden, kann unter Linux-Distributionen und Mac die "main.rb" aus dem "example"-Ordner als Computerspieler angegeben werden; unter Windows kann die "start.bat" ausgewählt werden.

Bitte nochmal korrekturlesen ("activity"?).

Beim Ruby-Client gibt es keine "start.bat". Sollte die noch hinzugefuegt werden? Wenn ja bitte einen Pull-Request im https://github.com/CAU-Kiel-Tech-Inf/socha_ruby_client

**Comment by soerendomroes** [comment]
Im example Ordner des ruby clients (da wo auch die main.rb ist) hab ich eine start.bat hinzugefügt im commit 34c7f016f9a56ce77ea12758b6f6f17ae6a19a17

**Comment by SKoschnicke** [comment]
Oh, das habe ich uebersehen. Okay! Aber bitte nochmal korrekturlesen.

**Comment by Xerus2000** [comment]
Bitte wieder öffnen wenn dieses Issue noch relevant ist.
